// Game data: regions and the evolution tree. Pure data, no behaviour.
// Loaded before sim.js. Attaches to window.GAME.
(() => {
  // Regions ------------------------------------------------------------------
  // pop is in millions. wealth drives how fast a region researches a cure and
  // how well it resists; heat/cold/damp/dry are climate scores in 0..1; urban
  // raises local spread; links lists the travel hubs a region has.
  const REGIONS = {
    canada: {
      name: "Canada",
      pop: 40,
      wealth: 0.9,
      heat: 0.1,
      cold: 0.9,
      damp: 0.4,
      urban: 0.8,
      links: "ap",
    },
    usa: {
      name: "United States",
      pop: 340,
      wealth: 0.95,
      heat: 0.4,
      cold: 0.4,
      damp: 0.5,
      urban: 0.83,
      links: "ap",
    },
    mexico: {
      name: "Mexico",
      pop: 130,
      wealth: 0.5,
      heat: 0.7,
      cold: 0.1,
      damp: 0.4,
      urban: 0.8,
      links: "ap",
    },
    camerica: {
      name: "Central America",
      pop: 52,
      wealth: 0.3,
      heat: 0.9,
      cold: 0,
      damp: 0.9,
      urban: 0.55,
      links: "p",
    },
    caribbean: {
      name: "Caribbean",
      pop: 44,
      wealth: 0.35,
      heat: 0.9,
      cold: 0,
      damp: 0.85,
      urban: 0.6,
      links: "ap",
    },
    colombia: {
      name: "Colombia",
      pop: 98,
      wealth: 0.45,
      heat: 0.85,
      cold: 0.05,
      damp: 0.85,
      urban: 0.8,
      links: "ap",
    },
    peru: {
      name: "Peru",
      pop: 47,
      wealth: 0.4,
      heat: 0.6,
      cold: 0.25,
      damp: 0.4,
      urban: 0.75,
      links: "p",
    },
    brazil: {
      name: "Brazil",
      pop: 216,
      wealth: 0.55,
      heat: 0.85,
      cold: 0,
      damp: 0.9,
      urban: 0.87,
      links: "ap",
    },
    argentina: {
      name: "Argentina",
      pop: 80,
      wealth: 0.6,
      heat: 0.4,
      cold: 0.3,
      damp: 0.5,
      urban: 0.9,
      links: "ap",
    },
    greenland: {
      name: "Greenland",
      pop: 0.06,
      wealth: 0.7,
      heat: 0,
      cold: 1,
      damp: 0.3,
      urban: 0.85,
      links: "p",
      jumpy: true,
    },
    iceland: {
      name: "Iceland",
      pop: 0.39,
      wealth: 0.95,
      heat: 0,
      cold: 0.95,
      damp: 0.5,
      urban: 0.94,
      links: "a",
      jumpy: true,
    },
    uk: {
      name: "United Kingdom",
      pop: 74,
      wealth: 0.92,
      heat: 0.2,
      cold: 0.4,
      damp: 0.7,
      urban: 0.85,
      links: "ap",
    },
    weurope: {
      name: "Western Europe",
      pop: 105,
      wealth: 0.93,
      heat: 0.3,
      cold: 0.3,
      damp: 0.6,
      urban: 0.82,
      links: "ap",
    },
    iberia: {
      name: "Iberia",
      pop: 59,
      wealth: 0.82,
      heat: 0.6,
      cold: 0.1,
      damp: 0.3,
      urban: 0.8,
      links: "ap",
    },
    ceurope: {
      name: "Central Europe",
      pop: 103,
      wealth: 0.94,
      heat: 0.3,
      cold: 0.45,
      damp: 0.55,
      urban: 0.76,
      links: "a",
    },
    scandinavia: {
      name: "Scandinavia",
      pop: 27,
      wealth: 0.96,
      heat: 0.05,
      cold: 0.85,
      damp: 0.5,
      urban: 0.86,
      links: "ap",
    },
    italy: {
      name: "Italy",
      pop: 59,
      wealth: 0.85,
      heat: 0.55,
      cold: 0.2,
      damp: 0.45,
      urban: 0.72,
      links: "ap",
    },
    balkans: {
      name: "Balkans",
      pop: 42,
      wealth: 0.6,
      heat: 0.5,
      cold: 0.3,
      damp: 0.5,
      urban: 0.6,
      links: "p",
    },
    eeurope: {
      name: "Eastern Europe",
      pop: 90,
      wealth: 0.65,
      heat: 0.2,
      cold: 0.6,
      damp: 0.5,
      urban: 0.65,
      links: "a",
    },
    russia: {
      name: "Russia",
      pop: 144,
      wealth: 0.65,
      heat: 0.05,
      cold: 0.95,
      damp: 0.4,
      urban: 0.75,
      links: "ap",
    },
    casia: {
      name: "Central Asia",
      pop: 120,
      wealth: 0.3,
      heat: 0.6,
      cold: 0.5,
      damp: 0.1,
      urban: 0.45,
      links: "a",
    },
    turkey: {
      name: "Turkey",
      pop: 100,
      wealth: 0.6,
      heat: 0.5,
      cold: 0.3,
      damp: 0.35,
      urban: 0.77,
      links: "ap",
    },
    iran: {
      name: "Iran",
      pop: 90,
      wealth: 0.45,
      heat: 0.7,
      cold: 0.2,
      damp: 0.15,
      urban: 0.77,
      links: "ap",
    },
    mideast: {
      name: "Middle East",
      pop: 85,
      wealth: 0.5,
      heat: 0.8,
      cold: 0.05,
      damp: 0.15,
      urban: 0.8,
      links: "a",
    },
    arabia: {
      name: "Arabia",
      pop: 85,
      wealth: 0.8,
      heat: 1,
      cold: 0,
      damp: 0.1,
      urban: 0.85,
      links: "ap",
    },
    egypt: {
      name: "Egypt",
      pop: 112,
      wealth: 0.35,
      heat: 0.95,
      cold: 0,
      damp: 0.05,
      urban: 0.43,
      links: "ap",
    },
    nafrica: {
      name: "North Africa",
      pop: 105,
      wealth: 0.4,
      heat: 0.85,
      cold: 0,
      damp: 0.1,
      urban: 0.65,
      links: "ap",
    },
    wafrica: {
      name: "West Africa",
      pop: 250,
      wealth: 0.15,
      heat: 0.95,
      cold: 0,
      damp: 0.6,
      urban: 0.45,
      links: "p",
    },
    nigeria: {
      name: "Nigeria",
      pop: 225,
      wealth: 0.25,
      heat: 0.95,
      cold: 0,
      damp: 0.75,
      urban: 0.54,
      links: "ap",
    },
    cafrica: {
      name: "Central Africa",
      pop: 200,
      wealth: 0.12,
      heat: 0.9,
      cold: 0,
      damp: 0.9,
      urban: 0.48,
      links: "p",
    },
    sudan: {
      name: "Sudan",
      pop: 65,
      wealth: 0.15,
      heat: 1,
      cold: 0,
      damp: 0.15,
      urban: 0.35,
      links: "p",
    },
    eafrica: {
      name: "East Africa",
      pop: 340,
      wealth: 0.2,
      heat: 0.8,
      cold: 0,
      damp: 0.6,
      urban: 0.3,
      links: "ap",
    },
    safrica: {
      name: "Southern Africa",
      pop: 150,
      wealth: 0.35,
      heat: 0.7,
      cold: 0.05,
      damp: 0.4,
      urban: 0.55,
      links: "ap",
    },
    madagascar: {
      name: "Madagascar",
      pop: 30,
      wealth: 0.1,
      heat: 0.8,
      cold: 0,
      damp: 0.7,
      urban: 0.4,
      links: "p",
      jumpy: true,
    },
    pakistan: {
      name: "Pakistan",
      pop: 240,
      wealth: 0.25,
      heat: 0.85,
      cold: 0.1,
      damp: 0.3,
      urban: 0.38,
      links: "ap",
    },
    india: {
      name: "India",
      pop: 1650,
      wealth: 0.3,
      heat: 0.9,
      cold: 0.05,
      damp: 0.7,
      urban: 0.36,
      links: "ap",
    },
    china: {
      name: "China",
      pop: 1430,
      wealth: 0.65,
      heat: 0.5,
      cold: 0.35,
      damp: 0.55,
      urban: 0.65,
      links: "ap",
    },
    korea: {
      name: "Korea",
      pop: 78,
      wealth: 0.85,
      heat: 0.35,
      cold: 0.45,
      damp: 0.6,
      urban: 0.8,
      links: "ap",
    },
    japan: {
      name: "Japan",
      pop: 124,
      wealth: 0.93,
      heat: 0.4,
      cold: 0.35,
      damp: 0.75,
      urban: 0.92,
      links: "ap",
    },
    seasia: {
      name: "Southeast Asia",
      pop: 300,
      wealth: 0.4,
      heat: 0.95,
      cold: 0,
      damp: 0.95,
      urban: 0.5,
      links: "ap",
    },
    philippines: {
      name: "Philippines",
      pop: 115,
      wealth: 0.3,
      heat: 0.95,
      cold: 0,
      damp: 0.9,
      urban: 0.48,
      links: "ap",
    },
    indonesia: {
      name: "Indonesia",
      pop: 290,
      wealth: 0.35,
      heat: 0.95,
      cold: 0,
      damp: 0.95,
      urban: 0.58,
      links: "ap",
    },
    australia: {
      name: "Australia",
      pop: 27,
      wealth: 0.93,
      heat: 0.75,
      cold: 0,
      damp: 0.3,
      urban: 0.87,
      links: "ap",
    },
    nz: {
      name: "New Zealand",
      pop: 7,
      wealth: 0.9,
      heat: 0.3,
      cold: 0.2,
      damp: 0.6,
      urban: 0.85,
      links: "ap",
      jumpy: true,
    },
  };

  for (const key of Object.keys(REGIONS)) {
    const r = REGIONS[key];
    r.key = key;
    r.dry = 1 - r.damp;
    r.air = r.links.includes("a");
    r.sea = r.links.includes("p");
  }

  // Evolution tree -----------------------------------------------------------
  // Each trait: id, tab, name, cost in research points, [col, row] on the hex
  // grid, needs (all prerequisites), and the stat changes it applies.
  //
  // Stat keys, all additive multipliers on the simulation's base rates:
  //   spread     local spread rate
  //   heat/cold  spread bonus in hot / cold regions
  //   damp/dry   spread bonus in humid / arid regions
  //   poor/rich  spread bonus in low- / high-wealth regions
  //   plane/boat chance a traveller carries it out along that route
  //   notice     how visible it is, which brings the response forward
  //   severity   public alarm: more research points per case, faster cure
  //   lethal     deaths per infected per day
  //   resist     slows cure research
  const TRAITS = [
    // --- Spread -------------------------------------------------------------
    [
      "drift1",
      "spread",
      "Drift I",
      7,
      0,
      0,
      [],
      { spread: 0.35, dry: 0.25, plane: 0.3, notice: 0.02 },
    ],
    [
      "drift2",
      "spread",
      "Drift II",
      14,
      0,
      1,
      ["drift1"],
      { spread: 0.5, dry: 0.3, plane: 0.5, notice: 0.03 },
    ],
    [
      "drift3",
      "spread",
      "Drift III",
      21,
      0,
      2,
      ["drift2"],
      { spread: 0.7, dry: 0.3, plane: 0.8, notice: 0.05 },
    ],
    [
      "water1",
      "spread",
      "Water I",
      8,
      1,
      0,
      [],
      { spread: 0.3, damp: 0.3, boat: 0.35, notice: 0.02 },
    ],
    [
      "water2",
      "spread",
      "Water II",
      15,
      1,
      1,
      ["water1"],
      { spread: 0.5, damp: 0.35, boat: 0.6, notice: 0.03 },
    ],
    [
      "water3",
      "spread",
      "Water III",
      22,
      1,
      2,
      ["water2"],
      { spread: 0.7, damp: 0.35, boat: 0.9, notice: 0.05 },
    ],
    ["vector1", "spread", "Vector I", 12, 2, 1, ["water1"], { spread: 0.35, heat: 0.4, poor: 0.3 }],
    [
      "vector2",
      "spread",
      "Vector II",
      20,
      2,
      2,
      ["vector1"],
      { spread: 0.5, heat: 0.5, poor: 0.4, boat: 0.3 },
    ],
    [
      "livestock",
      "spread",
      "Livestock",
      16,
      3,
      1,
      ["drift1"],
      { spread: 0.4, poor: 0.5, plane: 0.2 },
    ],
    [
      "rodent",
      "spread",
      "Rodent",
      18,
      3,
      2,
      ["livestock"],
      { spread: 0.45, cold: 0.4, poor: 0.4, boat: 0.4 },
    ],
    [
      "crowding",
      "spread",
      "Crowding",
      19,
      2,
      3,
      ["vector1"],
      { spread: 0.6, rich: 0.3, plane: 0.3 },
    ],
    [
      "extremophile",
      "spread",
      "Extremophile",
      26,
      1,
      3,
      ["water2"],
      { heat: 0.5, cold: 0.5, damp: 0.3, dry: 0.3 },
    ],

    // --- Traits (what it does to carriers) ----------------------------------
    ["fatigue", "traits", "Fatigue", 4, 0, 0, [], { spread: 0.1, severity: 0.4, notice: 0.03 }],
    [
      "cough",
      "traits",
      "Cough",
      6,
      1,
      0,
      ["fatigue"],
      { spread: 0.35, severity: 0.8, notice: 0.05, plane: 0.2 },
    ],
    [
      "fever",
      "traits",
      "Fever",
      9,
      2,
      0,
      ["fatigue"],
      { spread: 0.25, severity: 1.4, lethal: 0.0004, notice: 0.08 },
    ],
    ["rash", "traits", "Rash", 7, 0, 1, ["fatigue"], { severity: 1, notice: 0.1 }],
    [
      "insomnia",
      "traits",
      "Insomnia",
      8,
      1,
      1,
      ["cough"],
      { spread: 0.2, severity: 1.2, notice: 0.04 },
    ],
    [
      "chills",
      "traits",
      "Chills",
      11,
      2,
      1,
      ["fever"],
      { spread: 0.3, severity: 1.8, lethal: 0.0012, cold: 0.2 },
    ],
    ["anaemia", "traits", "Anaemia", 13, 0, 2, ["rash"], { severity: 2.2, lethal: 0.002 }],
    [
      "seizure",
      "traits",
      "Seizure",
      17,
      1,
      2,
      ["insomnia"],
      { severity: 3, lethal: 0.004, notice: 0.12 },
    ],
    [
      "collapse",
      "traits",
      "Collapse",
      22,
      2,
      2,
      ["chills"],
      { severity: 4.5, lethal: 0.012, notice: 0.18 },
    ],
    [
      "necrosis",
      "traits",
      "Necrosis",
      30,
      1,
      3,
      ["seizure", "anaemia"],
      { severity: 6, lethal: 0.03, notice: 0.25 },
    ],
    [
      "cascade",
      "traits",
      "Cascade",
      44,
      2,
      3,
      ["collapse"],
      { severity: 9, lethal: 0.09, notice: 0.4 },
    ],

    // --- Shielding ----------------------------------------------------------
    ["cold1", "shield", "Cold Shield I", 9, 0, 0, [], { cold: 0.45 }],
    ["cold2", "shield", "Cold Shield II", 17, 0, 1, ["cold1"], { cold: 0.6 }],
    ["heat1", "shield", "Heat Shield I", 9, 1, 0, [], { heat: 0.45 }],
    ["heat2", "shield", "Heat Shield II", 17, 1, 1, ["heat1"], { heat: 0.6 }],
    ["damp1", "shield", "Damp Shield", 11, 2, 0, [], { damp: 0.5 }],
    ["dry1", "shield", "Dry Shield", 11, 3, 0, [], { dry: 0.5 }],
    ["generic1", "shield", "Drug Tolerance I", 14, 2, 1, ["damp1"], { resist: 0.18, rich: 0.2 }],
    ["generic2", "shield", "Drug Tolerance II", 24, 2, 2, ["generic1"], { resist: 0.3, rich: 0.3 }],
    ["stealth1", "shield", "Low Profile I", 12, 3, 1, ["dry1"], { notice: -0.3 }],
    [
      "stealth2",
      "shield",
      "Low Profile II",
      22,
      3,
      2,
      ["stealth1"],
      { notice: -0.45, resist: 0.12 },
    ],
    ["shuffle", "shield", "Shuffle", 34, 1, 2, ["cold2", "heat2"], { resist: 0.45, spread: 0.2 }],
    [
      "dormant",
      "shield",
      "Dormancy",
      40,
      0,
      2,
      ["cold2"],
      { resist: 0.35, notice: -0.5, spread: 0.3 },
    ],
  ];

  const TRAIT_LIST = TRAITS.map(([id, tab, name, cost, col, row, needs, fx]) => ({
    id,
    tab,
    name,
    cost,
    col,
    row,
    needs,
    fx,
  }));

  const TRAIT_BY_ID = {};
  for (const t of TRAIT_LIST) TRAIT_BY_ID[t.id] = t;

  const TABS = [
    { id: "spread", name: "Spread" },
    { id: "traits", name: "Traits" },
    { id: "shield", name: "Shielding" },
  ];

  // How each stat reads in the trait panel. sign true means "higher is worse
  // for you" and gets shown in the warning colour.
  const FX_LABELS = {
    spread: ["Spread", "x"],
    heat: ["Hot regions", "x"],
    cold: ["Cold regions", "x"],
    damp: ["Humid regions", "x"],
    dry: ["Arid regions", "x"],
    poor: ["Poorer regions", "x"],
    rich: ["Wealthy regions", "x"],
    plane: ["Air routes", "x"],
    boat: ["Sea routes", "x"],
    notice: ["Detection", "warn"],
    severity: ["Alarm", "warn"],
    lethal: ["Deaths", "warn"],
    resist: ["Cure resistance", "x"],
  };

  // Starting conditions ------------------------------------------------------
  const DIFFICULTIES = [
    {
      id: "casual",
      name: "Casual",
      blurb: "Slow research, careless hygiene, borders stay open a long while.",
      cureRate: 0.7,
      hygiene: 0.7,
      pointBonus: 1.25,
    },
    {
      id: "normal",
      name: "Normal",
      blurb: "Governments react at a sensible pace. The intended game.",
      cureRate: 0.88,
      hygiene: 1,
      pointBonus: 1,
    },
    {
      id: "brutal",
      name: "Brutal",
      blurb: "Fast labs, clean hands, and borders that slam shut early.",
      cureRate: 1.6,
      hygiene: 1.35,
      pointBonus: 0.8,
    },
  ];

  const STRAINS = [
    {
      id: "spore",
      name: "Spore",
      blurb: "The plain starting strain. No tricks, no handicap.",
      fx: {},
      note: "",
    },
    {
      id: "brittle",
      name: "Brittle",
      blurb: "Spreads fast but dies off outside its comfort zone.",
      fx: { spread: 0.45, heat: -0.3, cold: -0.3 },
      note: "Shielding costs 20% less.",
      shieldDiscount: 0.2,
    },
    {
      id: "quiet",
      name: "Quiet",
      blurb: "Hard to notice, slow to get going. Buys you time to build.",
      fx: { notice: -0.45, spread: -0.2, resist: 0.1 },
      note: "Labs start later.",
      cureDelay: 0.25,
    },
  ];

  window.GAME = { REGIONS, TRAIT_LIST, TRAIT_BY_ID, TABS, FX_LABELS, DIFFICULTIES, STRAINS };
})();
